//客户端模板数据配置列表
exports.xlsxList = [
    {input : "c_arenaHighRankAward"},
    {input : "c_exchange", valHandler : {strToObj:["item", "stuffs"]}},
    {input : "c_formula", idName : "name"},
    {input : "c_game", idName : "key", transer : "Game"},
    {input : "c_heroCall"},
    {input : "c_lottery", valHandler:{strToArrInArr:["one","range","ten","extra"]}},
    {input : "c_lvl", idName : "lvl", valHandler:{strToArr:["skillLimitLvlList", "skillGoldList"]}},
    {input : "c_mail", idName : "type"},
    {input : "c_msgCode", idName : "code", ignores : ["code", "remark", "range", "region0", "time"]},
    {input : "c_nameData"},
    {input : "c_open", idName : "key", ignores : ["key", "sys"]},
    {input : "c_prop", idName : "type", transer : "Prop"},
    {input : "c_rankReward", valHandler:{strToArrInArr:["arenaReward"]}},
    {input : "c_recharge"},
    {input : "c_robot", valHandler : {strToObj:["heros"]}},
    {input : "c_secret", valHandler : {strToArr:["heroIds"]}},
    {input : "c_shop", valHandler : {strToArrInArr:["items"]}},
    {input : "c_sign", valHandler : {strToObj:["item"]}},
    {input : "c_vip"},
    {input : "t_copy", valHandler : {strToArr : ["combatId", "copyBgId", "copySkillIds", "showTypes"]}},
    {input : "t_copyLoot", valHandler : {strToArr:["showItems","serverLootIds"], strToArrInArr : ["lootItems","wipeItems"]}},
    {input : "t_copyPrimary"},
    {input : "t_hero", ignores : ["note"]},
    {input : "t_item", valHandler:{strToArr:["copyIds"]}},
    {input : "t_itemEquip", valHandler : {strToArrInArr : ["props"], strToObj : ["stuffs"]}, ignores : ["note"]},
    {input : "t_itemEquipExclusive", valHandler:{strToArrInArr:["pAttackMult","pDefenceMult","mAttackMult","mDefenceMult","skill"]}, ignores : ["note"]},
    {input : "t_itemLogic", valHandler:{strToArrInArr:["create"]}},
    {input : "t_monster", valHandler:{strToArr:["skills"]}, ignores : ["note"]},
    {input : "t_skill", valHandler:{strToArr:["buffIds", "percentValue", "addValue", "propHurtMult", "buffNeedLvl"],strToArrInArr:["props", "targetArea", "buffTrigger"]}, ignores : ["note"]},
    {input : "t_serverLoot", valHandler:{strToArr:["itemIds"]}},
    {input : "t_skillDisplay", valHandler:{strToArr:["numberHurts"]}},
    {input : "t_task", valHandler:{strToArr:["nextIds", "timeLimit"], strToObj:["items"]}},
    {input : "t_warrior", valHandler:{strToArr:["skills", "defaultSkills","autoSkills"]}},
    {input:"c_guide2", idName:"groupId", transer : "Guide4Admin", valHandler:{strToObj:["option"], strToArr:["actions"]}, ignores : ["talk"]},
    {input:"c_loadModule",  ignores : []}
];
