/**
 * Created by Administrator on 2015/1/22.
 */
exports.dirCfg = {
    a_ac : "activity",
    a_ar : "arena",
    a_bs : "bonus",
    a_bo : "boss",
    a_de : "demonLotus",
    a_em : "mail",
    a_ev : "event",
    a_eq : "equip",
    a_u : "user",
    a_f : "friend",
    a_fi : "fight",
    a_ft: "fiveDaysTarget",
    a_g : "guild",
    a_gp : "guildPerson",
    a_gw : "guildWar",
    a_h : "honor",
    a_hs : "heartStunt",
    a_he : "hero",
    a_l:"lottery",
    a_t:"task",
    a_p : "pk",
    a_po : "pkOut",
    a_s : "shop",
    a_c : "copy",
    a_cc: "challengeCup",
    a_cr : "crystal",
    a_r : "rank",
    a_rb: "rebirth",
    a_rc : "recharge",
    a_re : "redEnvelope",
    a_rp : "redEnvelopePersonal",
    a_ch : "chat",
    a_co : "coupon",
    a_cof : "coffers",
    a_sd : "sdk",
    a_sm : "smelt",
    a_k : "king",
    a_it: "item",
    a_tr: "treasure",
    a_tm: "talisman",
    a_ex: "expedition",
    c_a : "account",
    c_n : "net",
    h_a : "account",
    h_nc : "notice",
    h_pc : "protocolContent",
    h_s : "serverInfo",
    h_cs: "kefu",
    admin_coffers: "coffers",
    admin_guild: "guild",
    admin_boss: "boss",
    admin_chat:"chat",
    admin_guildWar:"guildWar",
    admin_guildWarSync:"guildWarSync",
    admin_treasure:"treasure"
};
